### ISSUE TITLE
Implement the use of organism name

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1006]
Based on the decisions in #1005 implement the use of organism names.

**Dependencies:**
* #1005

**Comment by ReneRanzinger** [comment]
We decided which names to use. Based on the mockups in #1005 (last slide). The only change is from "slime mold" to "cellular slime molds". And for pig we will be using "pig"

**Comment by rykahsay** [comment]
I have done this.

@jeet-vora @kmartinez834 @Luke-Johnson-5 @ubhuiyan ... please check tst server and see if any pages contain scientific organism names like "Homo sapiens"


<img width="1325" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/fa8a8b57-36e2-4d46-b44f-fa4dac9fe359">

**Comment by kmartinez834** [comment]
- https://tst.glygen.org/glycan/G57789QC
Glycan Associated Protein and Biosynthetic Enzymes sections:
![image](https://github.com/glygener/glygen-issues/assets/90285371/951b2e28-a4eb-4273-84e5-c2064ccb7f15)
![image](https://github.com/glygener/glygen-issues/assets/90285371/9988f5cd-a8ef-453a-8f93-0dba38c091c7)

- https://tst.glygen.org/protein/P14210-1
Protein Homologs section:
![image](https://github.com/glygener/glygen-issues/assets/90285371/dbda71ac-8dcb-4b57-9a12-a33eca9d75e8)

**Comment by rykahsay** [comment]
@sujeetvkulkarni can you use the tax_common_name from the "glycoprotein" and "enzyme" objects as shown below:

<img width="468" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/733005c6-02aa-41de-afea-2cce13681b99">

<img width="566" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/3e40a1aa-6203-4de8-b5de-1c2758fd6cd4">

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 Homolog section in protein is similar to General section, contains both common and species name. So, I think we should not change Organism section in protein homolog section.

**Comment by kmartinez834** [comment]
@sujeetvkulkarni I think it just needs to be consistent.  On glycan page, Organism (in Organism section) is equal to the common name.  But on Protein page, Organism is equal to "species (common name)".   

--> Can we discuss this with the group on the Wednesday call?

**Comment by ReneRanzinger** [comment]
It’s not common name. Common name for both strains of HCV is HCV. It’s our chosen name, that in many case matches the common name.

See the organism mockup , last slide, last column.
Sent from my iPhone

On Mar 18, 2024, at 11:44 AM, Karina Martinez ***@***.***> wrote:

﻿ [EXTERNAL SENDER - PROCEED CAUTIOUSLY]


@sujeetvkulkarni<https://github.com/sujeetvkulkarni> I think it just needs to be consistent. On glycan page, Organism (in Organism section) is equal to the common name. But on Protein page, Organism is equal to "species (common name)".

--> Can we discuss this with the group on the Wednesday call?

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 yes, but you can expand (Show More...) and see species name in glycan organism section but here we have only one species so have kept those details in protein general and homolog section but will modify Glycan Associated Protein and Biosynthetic Enzymes sections (tables) just to show common name/chosen name.

Yes, we can discuss this with group in the call.

**Comment by kmartinez834** [comment]
To clarify, I think we need to discuss because the glycan and protein pages are now inconsistent.  

@ReneRanzinger we are using the term "Common Name" on the glycan page. Are you suggesting we should change this header since it's actually our chosen name?
![image](https://github.com/glygener/glygen-issues/assets/90285371/e3636057-c630-4295-be88-7822b0c9ab83)

**Comment by ReneRanzinger** [comment]
Not the marked place. That is the common name for this species.

I just wanted to make sure that “Organisms name” (that we should use in anll pages) and common name are not always the same.

Sent from my iPhone

On Mar 18, 2024, at 12:00 PM, Karina Martinez ***@***.***> wrote:

﻿ [EXTERNAL SENDER - PROCEED CAUTIOUSLY]


To clarify, I think we need to discuss because the glycan and protein pages are now inconsistent.

@ReneRanzinger<https://github.com/ReneRanzinger> we are using the term "Common Name" on the glycan page. Are you suggesting we should change this header since it's actually our chosen name?
image.png (view on web)<https://github.com/glygener/glygen-issues/assets/90285371/e3636057-c630-4295-be88-7822b0c9ab83>

**Comment by kmartinez834** [comment]
I see. In the example below, we are using "Cellular slime molds" for both Organism and Common Name.  However, Common Name should be Social amoeba per the [mockup](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/2.4/[Glycan_organism_display_1007.pptx](https://gwu0.sharepoint.com/:p:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Mockups/2.4/Glycan_organism_display_1007.pptx?d=wc445a13be8d341e1a2d2d0959aa1847b&csf=1&web=1&e=3XfbQ2)?d=wc445a13be8d341e1a2d2d0959aa1847b&csf=1&web=1&e=3XfbQ2).

https://tst.glygen.org/glycan/G85292WS
![image](https://github.com/glygener/glygen-issues/assets/90285371/1f7add8e-65ad-4cee-8b64-b35e53e1cdde)

Edited: Also, we're using "Cellular slime molds" (plural) instead of "Cellular slime mold" (as stated on the mockup)

**Comment by kmartinez834** [comment]
@rykahsay will you be changing to "Cellular slime mold" (singular) in 2.4?

**Comment by rykahsay** [comment]
I will do it in 2.5 -- already created a ticket for it #1189
