### ISSUE TITLE
Glycan detail highlight of substituents (sulfate)...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#1051]
See: https://www.glygen.org/glycan/G49743VF

Need to add: glymagesvg_substclass = "glymagesvg_high_opacity" to glymagesvg div. 

Also, the substituent(s) are not shown in the residues and/or enzymes section. The CHST8 CHST9 enzymes attach the 4-linked sulfate.

**Comment by sujeetvkulkarni** [comment]
@edwardsnj glymagesvg_substclass = "glymagesvg_high_opacity" will it work on motif details page too? I am trying to use it there in the div but its not highlighting sulfate there.

**Comment by edwardsnj** [comment]
I expect it to, depends on whether the motif has a sulfate. Actually, looks like the motif page already has this setting set correctly. See: https://www.glygen.org/motif/GGM.000049

**Comment by sujeetvkulkarni** [comment]
@edwardsnj got it thanks. glymagesvg_substclass = "glymagesvg_high_opacity"  change works on glycan details page. Motif details page works with or without change, so I will not make any changes on motif details page. I was looking at wrong motif.
Some of the missing enzymes are due to #1017. So should get resolved once the enzyme file is updated.
And sulfate not getting shown in Residues as @ReneRanzinger residue mapping file (json) sets a flag to ignore it.

**Comment by edwardsnj** [comment]
OK, just trying to make sure all of the bells and whistles I implemented are getting used! some of them were very difficult to make work! Cheers!
