### ISSUE TITLE
Identify why fruitfly EGFR does not have homologs in GlyGen

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1056]
@Luke-Johnson-5 

Go to OMA in /downloads folder in the server > OMA > current

In the current folder open the datasets fruitfly_*_oma_orthologs.txt  check if homologs are present for P04412 (EGFR).

Report the finding here

**Comment by Luke-Johnson-5** [comment]
@jeet-vora I believe that this protein is missing from all the fruitfly_*_oma_orthologs.txt files

![image](https://github.com/glygener/glygen-issues/assets/144174552/72353584-a842-472f-8198-56f25a1fab9e)

**Comment by jeet-vora** [comment]
@Luke-Johnson-5 Can you go to OMA and try to find the homologs? Try and download text files with UniProt ac and check. our downloads might have a problem.

SEE README IN THE OMA FOLDER TO GET AN IDEA

**Comment by Luke-Johnson-5** [comment]
@jeet-vora I followed up with that and I believe I have found the issue. Upon a closer look it appears that P04412 is being saved in this file by its OMA id instead of the UniProtKB id: (However, the Homolog's UniProtKB id are correct it seems)

![image](https://github.com/glygener/glygen-issues/assets/144174552/acf3623a-1622-466c-9b92-9fcfbba87645)
![image](https://github.com/glygener/glygen-issues/assets/144174552/7fcecabc-7f94-49ce-b050-01ebac660e31)

**Comment by Luke-Johnson-5** [comment]
This does not seem to be an isolated case currently there are 66 rows like this:
![image](https://github.com/glygener/glygen-issues/assets/144174552/ae5693fa-9724-49de-8d46-8990ac090f4d)
![image](https://github.com/glygener/glygen-issues/assets/144174552/fcae944a-a059-46b0-aa5b-5a17a62940ae)

**Comment by Luke-Johnson-5** [comment]
@jeet-vora  With the genome alliance Drosophila melanogaster Egfr site seeming to not [work](https://www.alliancegenome.org/gene/FB:FBgn0003731) I looked at flybase to see what they had for EGFR homologs [and this is what they had](https://flybase.org/cgi-bin/orthosearch.pl)

**Comment by Luke-Johnson-5** [comment]
I was also able to get a response rom the genome alliance api that contained this file.
[response_1707937857698.json](https://github.com/glygener/glygen-issues/files/14288472/response_1707937857698.json)
