### ISSUE TITLE
Missing Glycan: G16235VG

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1098]
https://www.glygen.org/protein/P13611-1#Glycan-Ligands

According to this section the protein binds G16235VG.

But if you click on the ID you learn its an expired ID.

**Comment by rykahsay** [comment]
@kmartinez834 @jeet-vora when I create the *_protein_matrixdb.csv datasets, I am not filtering out rows where the "saccharide" field contains glytoucan ID that is not in the glycan master list for the release. As a result, in version 2.4.1 which is currently on tst, the volume of these datasets is shrinking as follows:

human_protein_matrixdb.csv from 376 to 10
mouse_protein_matrixdb.csv from 68 to 2
rat_protein_matrixdb.csv from 461 to 0 

Since rat_protein_matrixdb.csv is empty, I am removed it from misc/dataset-masterlist.json and also retiring the corresponding BCO

**Comment by rykahsay** [comment]
Now fixed on tst, 

<img width="1301" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/758ab518-5b86-4229-938c-35d8b834e023">

**Comment by kmartinez834** [comment]
Removal of rows which do not contain GlyTouCan accessions resulted in the loss of publications with MatrixDB evidence badges:

Example of pub removed:
https://api.glygen.org/protein/detail/P55067

```
{
            "title": "Transport of a hyaluronan-binding protein in brain tissue.",
            "journal": "Matrix biology : journal of the International Society for Matrix Biology",
            "date": "2009",
            "authors": "Kappler J, Hegener O, Baader SL, Franken S, Gieselmann V, Haberlein H, Rauch U",
            "evidence": [
                {
                    "database": "MatrixDB",
                    "id": "GAG_9",
                    "url": "http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=GAG_9"
                },
                {
                    "database": "MatrixDB",
                    "id": "GAG_1",
                    "url": "http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=GAG_1"
                }
            ],
            "reference": [
                {
                    "type": "PubMed",
                    "id": "19576282",
                    "url": "https://glygen.org/publication/PubMed/19576282"
                }
            ]
        },
```

**Comment by kmartinez834** [comment]
Closing this ticket for 2.4

Will be continued in #1144 for 2.5 release
