### ISSUE TITLE
Suggest GlyGen organism name for HCV

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1215]
@katewarner will suggest some name(s) we can use as the GlyGen Organism name for the collapsed HCV organism annotation. For the specific species/isolate annotations we will be using the corresponding scientific name / common name.

**Comment by katewarner** [comment]
@ReneRanzinger 
1. Suggested name changes for “Hepatitis C virus (isolate H)”:
- Short/Common name change to “HCV-H77” because “HCV-H” is a different isolate. 
- Scientific name change to “Hepatitis C virus (isolate H77)” or (as in UniProt and NCBI taxa) “Hepatitis C virus genotype 1a (isolate H77)”
2. Suggested name change for “Hepatitis C virus (isolate Japanese)”:
- If  “Hepatitis C virus (isolate H) is changed to “Hepatitis C virus genotype 1a (isolate H77)”, then change “Hepatitis C virus (isolate Japanese)” to “Hepatitis C virus genotype 1b (isolate Japanese)”.

**Comment by ReneRanzinger** [comment]
Thanks for pointing this out we can put it on the agenda next Wednesday. I guess we decided for a different name since these names are very long and may disrupt the page layout (filters, statistic wideget ...).

But it was a misunderstanding. I thought you wanted to suggest a name for the glycan HCV species. We will collapse glycans from the species and the isolates into one organism. How should we name this organism? We could use the species name if we think that this is how people will look for it.

**Comment by katewarner** [comment]
@ReneRanzinger 

Oh I see. The current name for the HCV species in NCBI is “Hepacivirus hominis”, although Hepacivirus C is an accepted synonym so I don't think it would be a problem if we wanted to keep the name.

**Comment by ReneRanzinger** [comment]
Accepted.
