### ISSUE TITLE
id mapping api failing with "Content-Type": "multipart/form-data"

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#123]
Id mapping api is failing with "Content-Type": "multipart/form-data" with input_idlist and or with userfile option.

userfile option,
https://api.tst.glygen.org/idmapping/search/
Content-Type: multipart/form-data;
parameters,

recordtype: protein
input_namespace: GeneID
output_namespace: UniProtKB
userfile: (binary)

input_idlist option,
https://api.tst.glygen.org/idmapping/search/
Content-Type: multipart/form-data;
parameters,

recordtype: protein
input_namespace: GeneID
output_namespace: UniProtKB
input_idlist: 319164,319165,319166,319167,319170

**Comment by rykahsay** [comment]
I have tried to fix it -- and I am pointing the old idmapper test page to target tst APIs so that you can test it there. As you can see in the screenshot, the response is coming from  https://api.tst.glygen.org/idmapping/search


<img width="710" alt="image" src="https://user-images.githubusercontent.com/20584876/224101262-cddc5145-c2fa-4df0-9d21-e8837a474dde.png">

**Comment by sujeetvkulkarni** [comment]
0647b1b73ac932dc722b72b0519a3a1f73d0c70c
