### ISSUE TITLE
GlyTouCan accessions missing from glycan_classification.csv

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#125]
-  Source file `downloads/glytoucan/current/export/classifcation.tsv` has 31288 unique accessions in with GlycanType or GlycanSubtype classification
- `unreviewed/glycan_classification.csv` has 30942 unique accessions
--> why were these glycan excluded?  

See below for examples of missing glytoucan accessions:
G49108TO
G00058XR
G00194GV
G01002UX

**Comment by rykahsay** [comment]
My script was expecting subtype values to start with words "N-linked" or "O-linked". These were skipped because subtype is simply "O-GlcNAc". To fix this, I have taken the liberty to read this as "O-linked O-GlcNAc". These glycans are not in unreviewed/glycan_classification.csv and I am making all proteoform datasets again. Please check (after few hours) and make sure the missing glycosylation rows that correspond to these glytoucans are present now

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/20584876/224149842-eb1d0b50-fb3a-4c37-87a6-d075e1f047d2.png">

**Comment by kmartinez834** [comment]
Please do the same for "O-mannose" and "O-fucose" (O-linked) and "Keratan sulfate" (GAG)

**Comment by rykahsay** [comment]
Done.  I am making all proteoform datasets again. Please check (after few hours) and make sure the missing glycosylation rows that correspond to these glytoucans are present now

**Comment by kmartinez834** [comment]
👍 All glytoucan accessions are present in both files
👍 Verified that G49108TO is present in proteoform files
