### ISSUE TITLE
Advanced search organism list

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1325]
In both glycan and protein advanced search, organism drop down list:
- HCV is listed twice
- Baker's yeast and Social amoeba are common names, not GlyGen names 
- Glycan also includes "thale-cress", "chinese hampsters" and "rattus"
![image](https://github.com/glygener/glygen-issues/assets/90285371/4260450e-8ba5-456a-9963-fffb468a5245)

Update search_init APIs with "glygen_name" from misc/species_info.csv. Do not include if "glygen_name" is blank.

**Comment by rykahsay** [comment]
check now

**Comment by kmartinez834** [comment]
@katewarner I'm assigning to you.  Try to check the issues I brought up, let me know if you have questions.

**Comment by katewarner** [comment]
The issues above are fixed and the protein advanced search is looking good. 

However, I checked with Rene and he confirmed that we should remove "HCV-H77" from the Glycan Advanced search (https://tst.glygen.org/glycan-search/) organism list because users should only be able to restrict their advanced search to HCV (Tax ID: 3052230) for glycans. However, the HCV-H77 (Tax ID: 63746) information will still be present in the organism section of the glycan detail page (see https://github.com/glygener/glygen-issues/issues/1205).

**Comment by rykahsay** [comment]
@katewarner  and @kmartinez834  ... can you please come up with a documentation that details the set of agreements the team has made in terms of dealing with taxonomy issues. The document should itemize all the agreements we have reached ... 

That is the only way I can handle these issues ....

**Comment by ReneRanzinger** [comment]
To avoid the additional species entries (e.g. Chinese Hamster) coming from Nathan we decided to implement a white list strategy on our side. @rykahsay will work on this (#1487).

**Comment by kmartinez834** [comment]
Tax issues doc: https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/Shared%20Documents/Backend/Backend%20Workflow/Supplemental%20Files/GlyGen%20Organisms.docx?d=w4e505d8e40aa4bc5970cac7da288107d&csf=1&web=1&e=foW1YQ
