### ISSUE TITLE
Missing organism name

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1377]
https://tst.glygen.org/glycan/G02815KT#Organism

![chicken](https://github.com/glygener/glygen-issues/assets/2267640/3a325f56-10ea-4b6b-b149-8a8455a8ba8f)

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger 
I am using glygen_name for Organism column as per #1189. For "Chinese hamsters" there is no "glygen_name" value and I have assigned #1189 to @rykahsay for the this and other related changes.
@rykahsay needs to add glygen_name value for "Chinese hamsters".

https://tst.glygen.org/glycan/G17689DH#Organism

![Screenshot 2024-05-23 at 3 11 04 PM](https://github.com/glygener/glygen-issues/assets/13891482/4804b43c-a918-43f6-9ac7-be2f42bdfa02)

**Comment by kmartinez834** [comment]
@sujeetvkulkarni can you also collapse the Rat rows?  I think there should only be one row for Rat, and all genus and species annotations would appear when you click Show more...
![image](https://github.com/glygener/glygen-issues/assets/90285371/255392a4-249e-4d6d-a759-930e5302b804)

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 share the glycan id.

**Comment by kmartinez834** [comment]
@sujeetvkulkarni sorry, same as the one Rene referenced: https://tst.glygen.org/glycan/G02815KT#Organism

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 that's fine, I have addressed the issue. Earlier grouping was done at common_name level due to recent changes of showing glygen_name at the top this functionality was broken. I have made the changes now to group at glygen_name level and have fixed the issue. Please verify,
https://tst.glygen.org/glycan/G00031MO#Organism
https://tst.glygen.org/glycan/G02815KT#Organism

**Comment by kmartinez834** [comment]
Can confirm this is addressed
