### ISSUE TITLE
Plan biomarker update strategy

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1486]
Sit down with @DaniallMasood and @seankim658 to plan the biomarker update strategy for GlyGen. For 2.6 Robel added the files manual. Moving forward we need a sustainable strategy to download the files when we do the GlyGen data update. Since Robel prefers downloads over API calls a regular backup on the biomarker data page or in GitHub would be an option. Based on the decision the download scipts need to be updates.

Please keep in mind that biomarker are both glycan and protein related. Please decide how to divide the work. Glycan Biomarker may need to go to Nathan for the Glycan data update.

**Comment by ubhuiyan** [comment]
**Just an update:** @katewarner  and I will be meeting with Daniall and Sean next Tuesday (8/27) to determine the best way to download the biomarker data. We can report the main points of the discussion in the General Meeting on 09/4 (since I will be attending GlycoDay on 8/28). Since Nathan will be in Japan, we may have to wait until he's back to determine how best to provide him with the glycan biomarker data. Regardless, we will at least narrow down how we access biomarker data for now.

**Comment by jeet-vora** [comment]
@katewarner @ubhuiyan Add me and Cyrus to the meeting invite.

**Comment by ubhuiyan** [comment]
**Action Item:** Kate and Urnisha to create a script for downloading (and possibly filtering) biomarkers starting with release 2.7.

**Comment by seankim658** [comment]
@rykahsay @jeet-vora  Ok I figured out the "ftp" approach we discussed in the call today (9/9). It will be available by end of day tomorrow (9/10).

**Comment by seankim658** [comment]
@ubhuiyan @katewarner  https://hivelab.biochemistry.gwu.edu/biomarker-partnership/data/ftp/

Let me know if you have any questions.
