### ISSUE TITLE
Beta supersearch list API limit

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#1604]
**Beta supersearch list API limit**

when accessing the beta api for supersearch list with th following payload: '{
"id": "3b8199f848bc1d021fe3df8ad68068c0", "offset": 1, "sort": "hit_score", "limit": 100, "order": "desc", "filters": []
}
'
anything above a 99 limit results in an error:
{
"error_list": [
{
"error_code": "non-existent-search-results"
}
]
}

https://github.com/glygen-collab/ml.phospho-oglcnac/issues/3

**Comment by rykahsay** [comment]
Please report both the search and list API calls

**Comment by rykahsay** [comment]
Like I mentioned earlier, cache id= 3b8199f848bc1d021fe3df8ad68068c0  has been cleared and you need to give me the search query used or new cache id as shown below.

Given below is what I have tried to reproduce the issue and it doesn't seem to exist since I am getting list results for limit=150 as shown below:

https://beta.glygen.org/site-list/b6c014528fa08deb1eb309761e124116/sups

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/1740db43-a816-44fa-8978-4309f6c27615">

**Comment by jeet-vora** [comment]
Done
