### ISSUE TITLE
Quick search - Organism GT and GH always return the same list of enzymes

### ISSUE THREAD

**Issue by CyrusAY** [glygener/glygen-issues#1632]
1. What are the glycosyltransferases in Organism X?
2. What are the glycosylhydrolases in Organism X?
The search results of the above two questions outputs the same list of enzymes, regardless of organism:
<img width="689" alt="image" src="https://github.com/user-attachments/assets/11e33f48-df47-4f6b-9011-17942ac624a2">

I suspect the glycosylhydrolase question is pointing to the wrong data. There are indeed around 220 GT genes in human and the number of GH genes should be significantly smaller than that.

**Comment by rykahsay** [comment]
Check now:


<img width="1339" alt="image" src="https://github.com/user-attachments/assets/1e7c7c9d-d8a1-450c-9441-90e35ebf0d66">

**Comment by ubhuiyan** [comment]
@katewarner when you have the chance, do you mind verifying this? The numbers appear to still be the same among GHs and GTs.

**Comment by katewarner** [comment]
@rykahsay The glycosyltransferases datasets look good. However, the glycosyltransferases and glycosylhydrolases for each organism has the same number of entries and contain the same data. It looks like **glycosylhydrolases** data for all organisms is pointing to their **glycosyltransferases** data.

glycosyltransferases search results: 
![image](https://github.com/user-attachments/assets/5a623bbd-e868-494f-a1ea-dd3d2c4c144c)

glycosylhydrolases search results: 
![image](https://github.com/user-attachments/assets/355bbcea-1db4-4604-baa0-332bb6a2d1e4)

For all organisms please update the input file for their glycosylhydrolases data so it points to their glycohydrolase file `/data/projects/glygen/generated/datasets/unreviewed/*_protein_glycohydrolase.csv`

**Comment by rykahsay** [comment]
I cannot get to page you are giving on the screenshot, not specific enough --- which server? what did you search to get here? 

Can you do something about this type of incomplete reporting so that we don't waste time on back and forth?

TAG=incomplete_report

**Comment by katewarner** [comment]
Apologies, I thought you were aware of the server and page as you had replied to say that you had fixed Cyrus' issue, but the issue is not fixed so this relates to the original issue with Quick Search.

This issue occurs on both tst and beta. The page can be found here: `https://beta.glygen.org/quick-search/` and the issue was found within the Organisms section of this page and these two Quick Search questions: 
 
![image](https://github.com/user-attachments/assets/9785a5d3-a838-4b48-8850-a88a180a8605)
 
The issue is that if you select the same species for either question you get the same dataset i.e. the glycosyltransferase dataset for that species. For example is you select human for "What are the glycosyltransferases in Organism?" you get 220 proteins and if you select human for "What are the glycosylhydrolases in Organism?" you get 220 proteins but it should be 84 proteins (as shown in the screenshot in my last comment). 

```
[k.warner1@glygen-vm-dev unreviewed]$ awk -F, '{print $1}' /data/projects/glygen/generated/datasets/unreviewed/human_protein_glycohydrolase.csv | sort -u | grep -v "uniprot_ac" | wc -l
84
[k.warner1@glygen-vm-dev unreviewed]$ awk -F, '{print $1}' /data/projects/glygen/generated/datasets/unreviewed/human_protein_glycosyltransferase.csv | sort -u | grep -v "uniprot_ac" | wc -l
221
```
It looks like both questions are returning only the glycosyltransferases data for that species, when the  "What are the glycosylhydrolases in Organism?" query should only return the `species$_protein_glycohydrolase.csv ` datasets.

**Comment by rykahsay** [comment]
Please check now, given below is what I see after I fixed the issue

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/71ba784f-52a8-482f-b6c7-0a5d1ccc7fbb">

<img width="1146" alt="image" src="https://github.com/user-attachments/assets/2e411a9b-6313-425d-b1bc-dadfec47d01a">

**Comment by katewarner** [comment]
It's fixed. Thank you very much.

FYI @CyrusAY
