### ISSUE TITLE
protein_xref_biomuta 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1665]
The test link has been provided and examples. It should be good to go. 

```
[sbhuiyan28@glygen-vm-dev ~]$ cat /data/projects/glygen/generated/misc/xref_info.csv
protein_xref_biomuta,BioMuta,https://hive.biochemistry.gwu.edu/biomuta/proteinview/%s,Q8WXI7|A6NJZ7|P30613
```

**Comment by rykahsay** [comment]
@ubhuiyan @jeet-vora 

the URL https://hive.biochemistry.gwu.edu/biomuta/proteinview/P01116 will not work since the new prd BioMuta page will be https://hivelab.biochemistry.gwu.edu/biomuta/proteinview/P01116

Two solution options:

- inform UniProt and GlyGen to switch to the new URL
- work with @seankim658  to implement some forwarding of https://hive.biochemistry.gwu.edu/biomuta/proteinview/P01116 to https://hivelab.biochemistry.gwu.edu/biomuta/proteinview/P01116

**Comment by seankim658** [comment]
As far as I am aware, the old `hive.biochemistry` site is hosted on the old hive servers? I don't have access to that server but the forwarding would just be a reverse proxy `RewriteRule` that has to be done on the old hive server. Does that sound right? @rykahsay

**Comment by rykahsay** [comment]
@seankim658 
I have taken care of the GlyGen URL, and as for taking care of the links from UniProt, I have done  the Redirecting from the old hive server to hivelab pages. Here is another problem, UniProt is using "https://hive.biochemistry.gwu.edu/tools/biomuta/biomuta.php?gene=KRAS" instead of "https://hive.biochemistry.gwu.edu/biomuta/proteinview/P01116".

Again, I have done the Redirecting so that https://hive.biochemistry.gwu.edu/tools/biomuta/biomuta.php?gene=KRAS lands at https://hivelab.biochemistry.gwu.edu/biomuta/proteinview?gene=KRAS (shown bottom screenshot). With this, a couple of items need to be done between you and @Reeya123.

1. Reeya needs to detect gene=KRAS and make an API call by gene name instead 
2. You need to implement response by gene name in addition to by UniProtKB accession



<img width="640" alt="image" src="https://github.com/user-attachments/assets/988e1b61-ede1-4938-b291-2297d287c6b1">


<img width="672" alt="image" src="https://github.com/user-attachments/assets/b2681f8e-45fe-4765-8e71-221a693e2afa">

**Comment by rykahsay** [comment]
@jeet-vora  ... whatever approach we are following to make sure links from UniProtKB are not broken is a temporary solution since the old server will eventually retire and end up having broken links. You need to work with UniProt folks so that they change the link to https://hivelab.biochemistry.gwu.edu/biomuta/proteinview/P01116 (and similar for BioXpress)

**Comment by seankim658** [comment]
Tagging @Reeya123 for her awareness

**Comment by rykahsay** [comment]
Biomuta links are fixed now, please check

**Comment by ubhuiyan** [comment]
Looks good. Thanks guys!
