### ISSUE TITLE
Glycan/Proteoform QC datasets

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#1740]
QC of all datasets generated by Robel

**Comment by ubhuiyan** [comment]
### Protein Dataset QC

| Resource | QC by |Completed (Y/N)| Issue/Ticket | Notes | 
| -------- | ------- | ------- | ------- |------- |
|Genomics England |Kate | Y | Looks good |N |
|Genome Alliance |Kate | Y | Looks good |N |
|MGI |Kate | Y | Looks good |N |
|Mondo |Kate | Y | Looks good |N |
|EBI | Kate | Y | #1746 |missing gene co-ordinates 
|NCBI RefSeq | Kate| Y | No size change |N |
|Disease Ontology |Kate | Y |  | |
|Glycohydrolase (bovine) | Kate |  |  | |
|Glycosyltransferase (bovine) | Kate |  |  | |
|Protein Biomarker) | Kate |  |  | |

**Comment by ubhuiyan** [comment]
| QC category                                                          | Molecule   | Assignment   | Status (P/F\*\*) | Ticket Number | Instructions                                                                                                                                                                                                              | Notes |
| -------------------------------------------------------------------- | ---------- | ------------ | ---------------- | ------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----- |
 | Check Ready datasets for QC     |    Glycan   |    Urnisha              |     P          |           | Check logs/glycan.log to see which datasets are ready for QC |
 | Check datasets Manually for QC     |    Glycan   |    Urnisha              |        P       |           | Manually check if the datasets look good in unreviewed folder. Check size and check whether new datasets have been processed.<br>Check the dataset whose size is 0 of few KBs or Bs. Edit masterlist accordingly |
 | Check Datasets Group  | Glycan  |           Urnisha       |       P        |                                                                                                                                                                                       |   Run check-dataset-group.py -m glycan    |
| Check Dataset Citations | Glycan | Urnisha |    P      |               |  Run check-citation-datasets.py                                                                                                                                                                                        |       |
 | Check Ready datasets for QC     |    Proteoform   |    Urnisha              |       P        |           | Check logs/proteoform.log to see which datasets are ready for QC |
| Manual Check Datasets                                                | Proteoform | Urnisha |      P            |               | Manually check if the datasets look good in unreviewed folder. Check size and check whether new datasets have been processed.<br>Check the dataset whose size is 0 of few KBs or Bs. Edit masterlist accordingly          |
| Check  Datasets Group                                                | Proteoform | Urnisha |        P          |               | Run check-dataset-group.py -m proteoform                                                                                                                                                                                  |       |
| Global QC for Glycosylation, Phosphorylation, and Glycation Datasets | Proteoform | Urnisha |           P       |               | Run dump-global-qc-stats.py                                                                                                                                                                                               |       |
| Check Dataset Citations | Proteoform | Urnisha |     F      |               |  Run check-citation-datasets.py                                                                                                                                                                                        |       |

**Comment by ubhuiyan** [comment]
## Glycan Dataset QC
| Molecule  | Declined Dataset |  Issue/Explanation  | Ticket | 
| ------------- | ------------- |------------- | ------------- |
| Glycan  | glycan_citations_glytoucan.csv  | Rationale 2* | No ticket | 
| Glycan | glycan_citations_biomarkers.csv  | Rationale 1* | No ticket |
| Glycan | glycan_biomarkers.csv  | Rationale 1* | No ticket |

---------------------------------------------------------
### Rational 1 
```
[sbhuiyan28@glygen-vm-dev reviewed]$ wc -l glycan_biomarkers.csv 
95 glycan_biomarkers.csv
[sbhuiyan28@glygen-vm-dev unreviewed]$ wc -l glycan_biomarkers.csv 
18 glycan_biomarkers.csv
```
There is a significant decline in available glycan biomarkers. As previously discussed with the biomarker team, they have conducted data cleaning and merging which has resulted in this drop in glycan biomarkers. 

**Correspondence:** 
**Urnisha:** Awesome. Also, I noticed there are less glycan biomarkers. Sean mentioned you guys cleaned up the oncomx data. I assume this resulted in removing some biomarker assertions?

**Daniall:** yes some were removed or merged together. the conditions may have been wrong due to imisreading of the paper. so not so much biomarkers being removed but biomarker-disease associations being merged/fixed

----------------------------------------------------------
### Rational 2 
```
[sbhuiyan28@glygen-vm-dev reviewed]$ awk -F, '{print $1}' glycan_citations_glytoucan.csv | sort -u | wc -l
3926
[sbhuiyan28@glygen-vm-dev unreviewed]$ awk -F, '{print $1}' glycan_citations_glytoucan.csv | sort -u | wc -l
3915
```
Upon review, 11 citations were dropped from `glycan_citations_glytoucan.csv`, all linked to biomarkers. These appear to have been excluded by the biomarker team during data cleaning, similar to Rationale 1, where papers claiming unsupported biomarkers (based on listed PMIDs) were removed.

**Comment by ubhuiyan** [comment]
## Proteoform Dataset QC
| Molecule  | Declined Dataset |  Issue/Explanation  | Ticket | 
| ------------- | ------------- |------------- | ------------- |
| Proteoform  | human_proteoform_citations_glycosylation_sites_pdc_ccrcc.csv | Rationale 1* | #1671 | 
| Proteoform  | human_proteoform_phosphorylation_sites_iptmnet.csv  | Rationale 2* | No Ticket | 
| Proteoform  | mouse_proteoform_phosphorylation_sites_iptmnet.csv  | Rationale 2* |No Ticket | 
| Proteoform  | rat_proteoform_phosphorylation_sites_iptmnet.csv  | Rationale 2* | No Ticket | 
-------------------------------------------------------------------
### Rational 1 
```
[sbhuiyan28@glygen-vm-dev logs]$ awk -F, '{print $1, $4, $7, $10}' sbhuiyan28_qc_check_proteoform_datasets.csv | grep "-"
"-1359" "-25376" "-10" "human_proteoform_citations_glycosylation_sites_pdc_ccrcc.csv"
```
There is a significant decline in id and field count for this dataset. This decline is due to the global QC which identified multiple aa mismatches (as described by Kate in ticket #1671). Kate is initiating contact with the authors to resolve these mismatches. 

------------------------------------------------------------------
### Rational 2 

```
[sbhuiyan28@glygen-vm-dev iptmnet]$ wc -l 2024_06_20/ptm.txt 
1055800 2024_06_20/ptm.txt
[sbhuiyan28@glygen-vm-dev iptmnet]$ wc -l current/ptm.txt 
1055800 current/ptm.txt
[sbhuiyan28@glygen-vm-dev logs]$ wc -l /data/projects/glygen/generated/datasets/unreviewed/human_proteoform_phosphorylation_sites_iptmnet.csv
855003 /data/projects/glygen/generated/datasets/unreviewed/human_proteoform_phosphorylation_sites_iptmnet.csv
[sbhuiyan28@glygen-vm-dev logs]$ wc -l /data/shared/glygen/releases/data/v-2.6.1/reviewed/human_proteoform_phosphorylation_sites_iptmnet.csv 
855183 /data/shared/glygen/releases/data/v-2.6.1/reviewed/human_proteoform_phosphorylation_sites_iptmnet.csv
```
There appears to be a mild decline in the iptmnet datasets for human, mouse, and rat. Upon further investigation, it appears the change was due to flags such as `aa_mismatch` and `no-phosphorylation-record`. Given this, no ticket was created.

**Comment by ubhuiyan** [comment]
## Proteoform/Glycan Citation QC

| Molecule  | Citation Flag |  PMID  | Ticket | Rationale
| ------------- | ------------- |------------- | ------------- |  ------------- |
| Proteoform  | human_proteoform_phosphorylation_sites_iptmnet.csv | 26513018 | #1841  | Rationale 1*
| Proteoform  | rat_proteoform_glycosylation_sites_carbbank.csv| 93364082| #1568 | Will need to reach out to authors | 
| Proteoform  | human_proteoform_glycosylation_sites_carbbank.csv|93364082 | #1568  | Will need to reach out to authors |

-------------------------------------------------------
## Rationale 1
It appears PMID: 26513018 does not link to a publication when searched for on the PubMed website. This PMID was subsequently searched for in `human_proteoform_citations_phosphorylation_sites_iptmnet.csv`, but that PMID does not appear in the citations file. A ticket was created to notify Robel of this discrepancy: #1841 

```
[sbhuiyan28@glygen-vm-dev unreviewed]$ grep "26513018" human_proteoform_phosphorylation_sites_iptmnet.csv
"P38398-1","1552","Tyr","P42685-1","FRK","protein_xref_pubmed","26513018","protein_xref_iptmnet","P38398"
```

**Comment by ubhuiyan** [comment]
All QC has been completed and corresponding tickets for issues found have been created.
