### ISSUE TITLE
Push Protein BCOs to https://data.tst.glygen.org/

### ISSUE THREAD

**Issue by katewarner** [glygener/glygen-issues#1881]
All **protein BCOs** for 2.7 have been created and have passed the `check-bco2filename-mapping.py` check.

Please push the protein BCOs to TST #1742

**Comment by rykahsay** [comment]
I cannot push "protein BCOs" -- all BCOs have to be ready and there shouldn't be any error when you run "check-bco2filename-mapping.py". 

@ubhuiyan why don't we have BCO for rat_proteoform_glycosylation_sites_carbbank
```
NO-BCO,rat_proteoform_glycosylation_sites_carbbank.csv,ERROR,in_fs
```

**Comment by jeet-vora** [comment]
@rykahsay can you look at the ticket - https://github.com/glygener/glygen-issues/issues/1895

**Comment by ubhuiyan** [comment]
Hi all, yes once the rat carbbank dataset is removed from the reviewed file that BCO error should resolve. I have retired the dataset and citations BCOs as well. 

Otherwise, I see no other errors with proteoform or glycan BCOs/datasets. @rykahsay after you remove `rat_proteoform_glycosylation_sites_carbbank.csv`, please proceed with processing all BCOs. Thank you.
