### ISSUE TITLE
Protein Results Discrepancy in Super Search for Liver Cancer 

### ISSUE THREAD

**Issue by ubhuiyan** [glygener/glygen-issues#1976]
It appears there is a discrepancy with the number of protein results when searching for liver cancer by name and by DOID in the "Disease" field of the Super Search. This does not happen for ovarian, breast, or lung cancer. 

Example: 

Searching with DOID: 
![Search for 3571](https://github.com/user-attachments/assets/ed4ed1ae-ab61-41f2-8495-abcf57cf1045)

Searching with Disease Name: 
![Search for liver cancer](https://github.com/user-attachments/assets/48042b67-34a5-4f2e-8798-b2774b0c61bd)

**Comment by rykahsay** [comment]
I think this is not a problem and the reason is: when you search for "liver cancer", you are targeting all kind of names (recommended and synonyms) and looks like both recommended.name for DOID:3571 and synonym.name for DOID:684 are "liver cancer".


"liver cancer"
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/93eaa96e-683b-4c0b-ad9c-a1f9296868ff">


DOID:3571
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/6299f5f6-09ef-4f7a-80f0-a95184d53082">


DOID:684

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/be95cc15-b8b3-4b5d-9b10-ff32ae992686">
