### ISSUE TITLE
Re-push the BCOs before pushing 2.7 to prd

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#2000]
Re-push the BCOs before pushing 2.7 to prd as Kate and Urnisha have fixed some errors.

@katewarner @ubhuiyan

**Comment by rykahsay** [comment]
Which BCOs?

**Comment by jeet-vora** [comment]
@katewarner @ubhuiyan 
Provide the list to Robel of modified BCOs

**Comment by ubhuiyan** [comment]
The following BCO numbers have been modified (there may be some duplicates because we worked on the BCOs separately): 

- GLY_001151
- GLY_000517
- GLY_000631
- GLY_000632
- GLY_000633
- GLY_000807
- GLY_000935
- GLY_000959
- GLY_001107
- GLY_001171
- GLY_000040
- GLY_000041
- GLY_000221
- GLY_000479
- GLY_000628
- GLY_000708
- GLY_000709
- GLY_000710
- GLY_000711
- GLY_000806
- GLY_000955
- GLY_000962
- GLY_001105
- GLY_001172
- GLY_001151
- GLY_001152
- GLY_001153
- GLY_001154
- GLY_001155
- GLY_001156
- GLY_001157
- GLY_001158
- GLY_001160
- GLY_001161
- GLY_001162
- GLY_001163
- GLY_001216
- GLY_000482
- GLY_000629
- GLY_000887
- GLY_000953
- GLY_000567
- GLY_000568
- GLY_000569
- GLY_000678
- GLY_000803
- GLY_001111
- GLY_001184
- GLY_000143
- GLY_000004

- GLY_000024
- GLY_000025
- GLY_000028
- GLY_000029
- GLY_000038
- GLY_000042
- GLY_000084
- GLY_000092
- GLY_000138
- GLY_000225
- GLY_000268
- GLY_001176
- GLY_001180
- GLY_001171
- GLY_001172
- GLY_001185
- GLY_001183
- GLY_000841
- GLY_000843
- GLY_000886
- GLY_000868
- GLY_000827
- GLY_000823
- GLY_000826
- GLY_000965
- GLY_000694
- GLY_000724
- GLY_000130
- GLY_000729
- GLY_000139
- GLY_000709
- GLY_000631
- GLY_000030
- GLY_000039
- GLY_000043
- GLY_000330
- GLY_000026
- GLY_000695
- GLY_000725
- GLY_000730
- GLY_000251
- GLY_000231
- GLY_000710
- GLY_000279
- GLY_000224
- GLY_000226
- GLY_000331
- GLY_000280
- GLY_000524
- GLY_000816
- GLY_000731
- GLY_000613
- GLY_000471
- GLY_000419
- GLY_000896
- GLY_000928 
- GLY_000940
- GLY_000522 
- GLY_001173
- GLY_000608
- GLY_000609
- GLY_000804
- GLY_000679
- GLY_000540
- GLY_001113
- GLY_001114
- GLY_001116
- GLY_001165
- GLY_001166
- GLY_001167

**Comment by rykahsay** [comment]
I have tried to update prd, please check

**Comment by katewarner** [comment]
Looks good

**Comment by ubhuiyan** [comment]
I also think everything looks good. Thank you.
