### ISSUE TITLE
Implement download service for table data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#240]
Implement download according to the specs in #239 and for all the tables in the ticket.

**Dependencies**:
* #239 
* #296 

**Blocker for**:
* #241

**Comment by rykahsay** [comment]
Instead of one data download API (/data/download/), we have three data download APIs now. These three APIs are:

-  /data/list_download/ --> for downloading contents of search result pages
-  /data/detail_download/ --> for downloading contents of detail pages
-  /data/section_download/ --> for downloading contents of sections of derail pages

For example queries for the above three APIs can be found at https://github.com/glygener/glygen-backend-api/tree/2.1/tests/examples/data


<img width="711" alt="image" src="https://user-images.githubusercontent.com/20584876/234957478-88a29b94-894b-44cd-ac65-77032e338fac.png">
