### ISSUE TITLE
Integrate 2.1 data

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#263]
Integrate the data from the updates in #262. This is a sibling of #261 that deals with the glycan data.

**Dependencies**:
* #262

**Comment by jeet-vora** [comment]
@rykahsay You can process the following data sources

EBI - /data/projects/glygen/downloads/ebi/current
NCBI RefSeq - /data/projects/glygen/downloads/ncbi/refseq/current
O-GlcNAc DB (mcw_oglcnac) - /data/projects/glygen/downloads/mcw_oglcnac/current
Disease Ontology - /data/projects/glygen/downloads/do/current
MGI - /data/projects/glygen/downloads/mgi/current
Mondo - /data/projects/glygen/downloads/mondo/current
OMA - /data/projects/glygen/downloads/oma/current #366
iPTMnet - /data/projects/glygen/downloads/iptmnet/current
MatrixDB - /data/projects/glygen/downloads/matrixdb/current (#364)
Genomics England - /data/projects/glygen/downloads/genomics_england/current

*MatrixDB and Genomics England file format have been the same since it was last downloaded by Rahi. @JingyueWu

**Comment by rykahsay** [comment]
check

**Comment by jeet-vora** [comment]
Done
