### ISSUE TITLE
Glycan structure terms for paper curation

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#334]
* How many terms do not have a GlyTouCan ID (structure)?
* How many terms are missing a GlyTouCan ID (structure)?
* How many terms could we compute? Is there a document for this?
* What is the list of terms you will have to assign manually? Is there a document?

**Comment by Mindyporterfield** [comment]
There are 190 terms in all. 
58 of them are missing a structure. 
All terms with a structure have GlyTouCan Id's. 
The terms missing structures are commonly categorical terms rather than specific structures (ex triantennary, triantennary complex, Triantennary N-glycans, triantennary sialylated, triantennary trisialylated fucosylated). Many of these terms could be generated by looking at the structure and using a definition like we did in Grits. Some terms are classes/subclasses that could be defined by heirarchy. 
I have a spreadsheet I generated  for the terms. I sent you and Mike a link to it in email.

**Comment by Mindyporterfield** [comment]
[Glycan dictionary summary.xlsx](https://github.com/glygener/glygen-issues/files/11488204/Glycan.dictionary.summary.xlsx)

**Comment by ReneRanzinger** [comment]
I put the table into a [google sheet](https://docs.google.com/spreadsheets/d/1stP0u9T8HzL142JJwDWpnYtePVC8B0cIJS2O6U3yVHA/edit#gid=0). Please do the following:
* For terms that you can make a structure or substructure (e.g. Bisecting GlcNAc, dermatan sulfate) create a GWS file, a GlycoCT and an image file. Use the "glycan_dictionary_accession" from the wiki as the file name. Mark the rows with a color.
* For structures that we can solve programmatically with rules (e.g. Number of branches; Number of sialic acids) add columns after D and put the numbers in the cells (e.g. tetra antennary -> # Branches = 3). 
   * If a rule does not apply leave the cell empty. 
   * If its a range (e.g. sialated structure) use ">" (e.g. # Sia = >0). 
   * Make sure that the rules completely describe the target (e.g. # Branches = 3 is not enough for "Triantennary complex")
   * Also make a decision regarding subsets. For example is a "Sialated Triantennary complex" also a "Triantennary complex" or do we use **only** the more specific term?

**Comment by Mindyporterfield** [comment]
This is the latest version of the glycan terms to be  automated , @ReneRanzinger @mtiemeyer0919 I need help at this point especially with the gag and lipis terms

[Glycan dictionary summary4.xlsx](https://github.com/glygener/glygen-issues/files/11839946/Glycan.dictionary.summary4.xlsx)

**Comment by Mindyporterfield** [comment]
[GlycanDictionarySummary-7-12-2023](https://gwu0.sharepoint.com/:x:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B9165573A-027E-4CFF-85CF-06D8D0BC4C84%7D&file=Glycan.dictionary.summary7-12-2023.xlsx&action=default&mobileredirect=true)
