### ISSUE TITLE
Bad author order for pubmed paper...

### ISSUE THREAD

**Issue by edwardsnj** [glygener/glygen-issues#340]
Pubmed pages, e.g. https://glygen.org/publication/PubMed/25939779 list the authors in the wrong order.

Probable loading issue, but possibly a display issue.

**Comment by ReneRanzinger** [comment]
Backend issue or data issue. 

The API sends :
"authors" : "Clausen H., Kong Y., Rovira C., Hurtado-Guerrero R., Corzana F., Bernado P., Bernardes G.J., Bruscolini P., Companon I., Iglesias-Fernandez J., Lira-Navarrete E., Lostao A., Pallares M.C., Peregrina J.M., de Las Rivas M."

**Comment by rykahsay** [comment]
Nice catch -- some of our citations come from UniProtKB data (EBI) and the triples do not indicate order of authors. I have tried to correct this (now on tst):

<img width="1322" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7f51eb80-c335-4b18-99d9-a01da6205e15">

**Comment by edwardsnj** [comment]
Why am I assigned to this? Not fixed in production.

**Comment by rykahsay** [comment]
It is a protocol we are following. When one addresses an issue on the tst server, he/she re-assigns to the ticket to the "creator" for checking on the tst server. If the issue has been resolved on the tst server, then the "creator" closes the ticket. if not, "creator" comments about the unresolved issue and assigns back the ticket to the "assignee".

BTW, prd is being updated currently and this issue is fixed on prd as well.

**Comment by edwardsnj** [comment]
The example seems corrected. Hopefully this fixed any others with the same issue, but I don't have any way to verify this.
