### ISSUE TITLE
Resources with dead links

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#425]
- http://www.glycosciences.de/
- http://www.unicarbkb.org/

I already reached out to Matthew regarding UniCarbKB, waiting for response.

@jeet-vora @ReneRanzinger do you know who to contact about glycosciences.de?

**Comment by jeet-vora** [comment]
@kmartinez834 
We can try and contact the below unless Rene has more updated information.
Thomas Lütteke- [thomas@luetteke-online.de](mailto:thomas@luetteke-online.de) ( [glycosciences.de](http://glycosciences.de/) is maintained by his group)

Andreas Bohne-Lang - [andreas.bohne-lang@medma.uni-heidelberg.de](mailto:andreas.bohne-lang@medma.uni-heidelberg.de)

**Comment by ReneRanzinger** [comment]
Its Thomas. Andreas left the domain 2005. Do you want me to contact him?

**Comment by jeet-vora** [comment]
@ReneRanzinger Please do

**Comment by ReneRanzinger** [comment]
Hi Thomas,

I hope you are doing well. We are currently testing the new release candidate for our GlyGen portal and noticed that all Glycosciences.de links are no longer working (408 - Connection timeout). I was wondering if you please can check on that and let us know the status of the server. 

Thank you,
  René

**Comment by ReneRanzinger** [comment]
Hi René,

the server is currently offline because our central computing department found some security issues, which I need to fix before the IP is made publicly accessible again. This takes longer than expected because upgrade to current version of e.g. PHP need adaptions in the old code, and because I currently have to teach 4 days per week, so there is hardly any time for anything else. Teaching takes another four weeks, after that I hope that there will be more time for the server.

Best regards
Thomas

**Comment by kmartinez834** [comment]
Resolution tracked in #431

**Comment by kmartinez834** [comment]
From: Matthew Campbell
Tue, Jun 13, 2023 at 3:53 PM
To: "Martinez, Karina"

Hi Karina,

I am in the process of moving this resource and will have it back up and running in a few weeks.

All the best,
Matthew
