### ISSUE TITLE
Blast not working

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#440]
Used example UniProtKB accession/sequence and default values.

https://tst.glygen.org/blast-result/46
![image](https://github.com/glygener/glygen-issues/assets/90285371/bbfd6edf-82ac-4c58-aa49-fb84aa124767)

**Comment by rykahsay** [comment]
@sujeetvkulkarni  @ReneRanzinger -- it looks like the front end cannot handle if the BLAST results API response is big. Results for jobid=57 on tst server are found by submitting full sequence of the example UniProtKB accession (retrieve sequence first). As you can see on the screenshots given below, the results API is responding but both the swagger and your frontend code seem to have a problem. Swagger says "RangeError: Maximum call stack size exceeded" which seems to me the javascript process is having hard time to consume the response because of memory limitations ( .. not sure ?)


<img width="986" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/66d3a44e-b181-4950-9ff8-6d3c4b826548">

<img width="1015" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/7be3e7c7-5dfd-42e1-b0a6-fc11a017233d">


<img width="658" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/8bf17c36-8f62-4d9b-8374-e77439ae8c54">

**Comment by sujeetvkulkarni** [comment]
Used example (P14210) UniProtKB accession/sequence and default values.


@rykahsay looks like backend is not sending all the protein objects with proper schema format. Some protein objects are missing sequences array. 
https://beta-api.glygen.org/job/results/?query={%22jobid%22:6}
in the above api response looks like below protein objects miss sequences array and cause frontend to fail.

Q5EBA7-1, W4VSR7-1, A0A096P6M7-1, Q80XZ3-1, D4A7D9-1, B2RYJ5-1, F1M9J3-1 , F1LTL7-1, Q80Z40-1
A0A0A0MXZ4-1, A0A0G2K797-1 , G3V8J3-1, A0A0G2JX19-1, A0A0G2K1V0-1, M0R4W8-1

Also, Q5EBA7-1, W4VSR7-1 etc does not have details: {} object.

other protein objects like P14210-1 contain proper schema and work well.

All protein objects should follow similar schema structure.

**Comment by sujeetvkulkarni** [comment]
I have filtered objects that dont contain sequences array and details objects - 426c94fe8352ad1bc1915fff5b6f89a2ad4e381a

**Comment by rykahsay** [comment]
@kmartinez834 --> please try now by submitting new job on beta (tst server is having firewall problems and Dacian is working on it)

**Comment by kmartinez834** [comment]
Working on beta now

**Comment by sujeetvkulkarni** [comment]
Add a log when filtering occurs - https://github.com/glygener/glygen-issues/issues/462
