### ISSUE TITLE
Wiki logging out/blocking

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#523]
Robel

Can you contact Dacian and ask him to not bar/block users from accessing Wiki when clicked a page/link is clicked several times. The users is blocked for 1 hour. Can you ask him to disable it.

wiki.glygen.org

**Comment by ReneRanzinger** [comment]
just to clarify. As soon as a navigate 2-4 pages on the wiki I will get blacklisted on the firewall. Most of you saw that happen live today. I went to wiki, searched for "dictionary" opened the structure dictionary page and (later) clicked on an image. And I was out. That is consistent (my home laptop, my home desktop, my work desktop). After this I am blacklisted and will be blocked for 1h for the entire glygen domain.

I understand the need for blocking of screenscappers that produce unwanted load but the behavior described up there is just normal surfing. That setting is way to tight. Thats especially annoying if I try to update a page and the blacklist happens when I enter the edit page mode. All my changes will be lost due to the blacklist. Interestingly, it does not happen if I use the GlyGen webportal. Maybe because its a single page application and all it does is call a bunch of web services for each "new page". While the wiki loads a new page with every click.

There is also a problem with the error message. Its just the standard "The connection has timed out" message. By now, I know it means I am blacklisted and have to be patient. But for a normal user that means ... webpage is broken - I am never coming back.

Please relax the conditions. Not just for me.
