### ISSUE TITLE
Request: API to connect to GNOME

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#539]
This was a request made during the game at the F2F meeting. @edwardsnj will contact Vijay to learn what exactly he is requesting.

**Comment by edwardsnj** [comment]
Email sent to Vijay:

Subject: Request for GNOme API...

Hi Vijay,

When we met for the F2F meeting in May, you submitted a request/suggestion for a GNOme API.

Since GNOme already has a number of APIs and/or web-services available, I thought I should understand your use-case a bit better. Perhaps the needed functionality is already available, or can be readily added.

What were you hoping a GNOme API could do for you?

Thanks,

- n
