### ISSUE TITLE
Discuss strategy to identify files to be downloaded by Nathan

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#563]
Currently the list of files to be downloaded by Nathan to make a glycan release are maintained in a google sheet. We discussed that an better alternative would be to have a CSV file on the server that tells which file + filename to download. It would allow Nathan to automate the retrieval of the file by 
1. Download this index (CSV) file
2. Read line by line and download the file with the filename as listed in the file

We need to see if this strategy is helpful. It certainly should stop Nathan from encountering unexpected file names. Let put it on one of the Wednesday meetings or we can also make this part of the developer meeting and invite Nathan.

**Comment by ReneRanzinger** [comment]
This was discussed with @edwardsnj in the [developer meeting on 8/16](https://gwu0.sharepoint.com/:w:/r/sites/GlyGenTeam-GRP/_layouts/15/Doc.aspx?sourcedoc=%7B7E992CE4-30A5-4A79-BD60-7C0F3F183115%7D&file=2023.08.16.docx&action=default&mobileredirect=true). @edwardsnj is OK with this, although he will not automate the process on his side it will still help to replace the Excel spreadsheet. 

@edwardsnj requested that before he processes the file in each version a script is run that will test that the files in the CSV file with the given filename do exists. @rykahsay will provide such a testing script for @kmartinez834 to be executed on a regular base. This will ensure that we will face the issue of incorrect file names (dead links) in the future.

@kmartinez834 provide an example for CSV file so @rykahsay can make a check script.

**Comment by kmartinez834** [comment]
I made a csv file and check script, saved here:
`misc/files4nathan.csv`
`/software/glygen/check-export-files.py`

@rykahsay @edwardsnj Currently, Nathan is accessing these files through the ln2downloads and ln2data links.  Would it be helpful to create a link just for Nathan that would contain the csv file and symbolic links to downloads and compiled folders?

**Comment by rykahsay** [comment]
I am assuming updating that file and running check-export-files.py will be part of your regular task whenever we start a new release.

**Comment by kmartinez834** [comment]
@rykahsay I created a symbolic link to the compiled folder from downloads, but the url isn't working: https://data.glygen.org/ln2downloads/compiled
--> Or would it be better to add a link to compiled from https://data.glygen.org/ln2data/?

Can you look into this?

**Comment by rykahsay** [comment]
That would not work because /data/projects/glygen/ is local to each server while /data/shared/glygen/ shared among all servers (dev/tst/prd). 

I just created /data/shared/glygen/downloads/compiled/ for you to place files you want to share with Nathan. These files will be available from all servers under:

 https://data.glygen.org/ln2downloads/compiled/
 https://beta-data.glygen.org/ln2downloads/compiled/
 https://data.tst.glygen.org/ln2downloads/compiled/


<img width="752" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/100e782b-11d8-45f9-8e63-3781ea90f2d9">

**Comment by kmartinez834** [comment]
I think there is some confusion.  I was trying to point a symbolic link to `/data/projects/glygen/generated/datasets/compiled/ `because Nathan is retrieving files from both `downloads` and `compiled` folders.

Is there a difference between https://data.glygen.org/ln2downloads/ and https://data.glygen.org/ln2data/downloads/?
--> If not, I'll instruct Nathan to use [ln2data ](https://data.glygen.org/ln2data/) only and you can delete the new `downloads/compiled/` folder

**Comment by kmartinez834** [comment]
Everything for Nathan will be at this URL: https://data.glygen.org/ln2downloads/export_files/
