### ISSUE TITLE
Downloads datasets from button without URL

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#585]
Rene,

We want to automate downloads from few resources that does not have a link/url but a download button. How can we do such downloads programmatically?

For eg O-GlcNAc DB

https://www.oglcnac.mcw.edu/download/
![image](https://github.com/glygener/glygen-issues/assets/25825266/28d76fe1-7191-4aad-bf1c-6b2adbf93f5f)

We download the reference datasets for organisms in GlyGen in csv format. 

There are other steps also associated along with downloading such as renaming, creating soft links and changing file/folder permissions. We generally have bash scripts for downloads.

**Comment by ReneRanzinger** [comment]
```
wget --no-check-certificate "https://www.oglcnac.mcw.edu/download/?oglcnac_format=csv&download_oglcnac=download_oglcnac&oglcnac_organisms=Bos+taurus" -O test.csv
```
If you are using another program just use the URL between the quotes. For other species replace the last part of the URL with the other species name. Make sure not to leave any whitespaces in the species name. Replace them with +. The "-O test.csv" is the output file name. You can change this to whatever you need, might save you same renaming. On my system I had to add the option "--no-check-certificate" because it does not recognize the certificate from their server. Try without first and if you get an error add the option back.

Let me know if you need more information or run into an issue.

**Comment by jeet-vora** [comment]
The command works well, it requires `--no-check-certificate` 
Many Thanks @ReneRanzinger 

`...../?oglcnac_format=csv&download_oglcnac=download_oglcnac&oglcnac_organisms=Bos+taurus`

**Question:** How did you come up with the highlighted part of the url? Can you share the documentation/site you used to write the command. If we need to change for other resource need to know how it would work for that resource.

**Comment by ReneRanzinger** [comment]
@jeet-vora Not much documentation. I was really just checking the source code of the webpage and with the knowledge how forms work build that part. If you like we can meet and can give you a quick tour? Maybe after the meeting next Wednesday?
