### ISSUE TITLE
Biomarker disease needs a type ahead key for protein and glycan search.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#627]

**Comment by rykahsay** [comment]
@sujeetvkulkarni @ReneRanzinger  ...

Sujeet,
Can you please give me a little bit more description (example APIs, screenshots) here? 

FYI, I always keep struggling to guess what exactly the issue is with some of the tickets you create.

If this is about typeahead APIs that target biomarker disease, given below are the examples

https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/typeahead/biomarker_disease_id.json
https://github.com/glygener/glygen-backend-api/blob/2.2/tests/examples/typeahead/biomarker_disease_name.json

Otherwise, I don't know that you mean by "ahead key".

**Comment by sujeetvkulkarni** [comment]
@rykahsay yes, I meant the field we specify in typeahead API for biomarker disease. I would certainly add more details in the tickets. Thanks for sharing examples.
Closing the ticket.
