### ISSUE TITLE
Script for all human BCOs

### ISSUE THREAD

**Issue by jeet-vora** [glygener/glygen-issues#643]
Write a script (parse-bcos.py) to pool all human BCOs in a text file. If possible, pool the BCOs in ascending order as per the dataset name.

**Comment by kmartinez834** [comment]
Per request from @jeet-vora , file was created for fruitfly instead of human. File saved at `/data/projects/glygen/generated/misc/fruitfly_bcos.txt`

Please take a look and let me know if you need any changes.  There are 71 fruitfly datasets, but only 68 BCOs because GLY_000653 contains 4 output files (not including stat files). File above contains the 68 concatenated BCOs, in alphabetical order of dataset name.

**Comment by jeet-vora** [comment]
Done
