### ISSUE TITLE
Release notes for 2.2

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#705]
Please create the release notes for 2.2:

- [x] @sujeetvkulkarni: [Portal release notes](https://wiki.glygen.org/Portal_release_notes/2.2)
- [x] @kmartinez834 Glycan/Proteoform [Data release notes](https://wiki.glygen.org/Data_release_notes)
- [x] @jeet-vora: Protein/Proteoform [Data release notes](https://wiki.glygen.org/Data_release_notes)
- [x] All: [Combined release notes](https://wiki.glygen.org/Release_notes)

**Comment by jeet-vora** [comment]
@kmartinez834 I have added protein notes. Please add the glycan notes [here](https://wiki.glygen.org/Data_release_notes) and [here](https://wiki.glygen.org/Index.php/Data_release_notes/2.2.1) and also in the [Combined release notes](https://wiki.glygen.org/Release_notes)

@ReneRanzinger @sujeetvkulkarni - Can we use past tense in [Combined release notes](https://wiki.glygen.org/Release_notes) like `Added` instead of `Add` | `Updated` instead of `Update`

**Comment by kmartinez834** [comment]
Done updating data release notes.  Have added to combined release notes.

Rene & Sujeet --> see Jeet's comment above

**Comment by sujeetvkulkarni** [comment]
@kmartinez834 , @jeet-vora done, please check.

**Comment by jeet-vora** [comment]
Checked and done.
