### ISSUE TITLE
Wiki page: GlyGen data repository - severe error

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#790]
The page for the GlyGen data repository in the wiki is broken. Really badly broken.There is only a stacktrace right now. 

Page: https://wiki.glygen.org/GlyGen_data_repository

You can also reach the page via a main box on the wiki homepage.

I would not find any other page that has this issue, still that should be fixed. Who would be able to work on this? Dacian, Robel?

**Comment by jeet-vora** [comment]
Contacted Robel and Dacian about the issue

**Comment by jeet-vora** [comment]
I recommend in the future to use at least the test instance for any changes to the wiki, and keep the test instance updated with the same data as the prod instance.
I have updated the dev instance to the latest mediawiki 1.40.1. I will continue to do so for the other two instances. Hopefully it will fix the issue.
Dacian

[image.png](https://mail.google.com/mail/u/0?ui=2&ik=6e1f9e425b&attid=0.2&permmsgid=msg-f:1778758020513851096&th=18af6afed21ae6d8&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ9IF1Opmh4AaBqq9N2nUwq8drpzQiHIq1xXLjMsb5orrv7bVMrcP4YFXiL-dNboYpMvjZovlz97BCTU9yZtZXttRUqgG9ge3ulyhvj-CC52ZKgk3C9ybHyBa68&disp=emb&realattid=ii_lnakk15n1)

[image.png](https://mail.google.com/mail/u/0?ui=2&ik=6e1f9e425b&attid=0.3&permmsgid=msg-f:1778758020513851096&th=18af6afed21ae6d8&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ9D5Xl-XjpqjTDm0QuvpMe5RR80I4b-y6EjRCff3hSK8G_KTjwzw8WFW9apf5_orTqc0cmG9GVt2jfN6YkWMrLMK5R6ujQFqWRt7IM054Uyge4mwkqcxUbCF3k&disp=emb&realattid=ii_lnakknvo2)

The problem was the TemplateStyles extension. I had to update it to the latest release (1_40).
Dacian
