### ISSUE TITLE
Process DO data for 2.3

### ISSUE THREAD

**Issue by JingyueWu** [glygener/glygen-issues#834]
Please process Disease Ontology data
/data/projects/glygen/downloads/do/current has been updated

please update the following datasets

protein_disease_idmap.csv
protein_disease_names.csv
*_protein_disease_glygen.csv
*_protein_disease_cdg.csv
*_protein_disease_genomics_england.csv
*_protein_disease_glyco.csv
*_protein_disease_glycosmos.csv
*_protein_disease_uniprotkb.csv
*_protein_disease_alliance_genome.csv
*_protein_disease_alliance_genome.csv

FYI - @jeet-vora

**Comment by jeet-vora** [comment]
@JingyueWu Always add the dataset names that gets processed from the DO dataset otherwise Robel will complain.

protein_disease_idmap.csv
protein_disease_names.csv
*_protein_disease_glygen.csv
*_protein_disease_cdg.csv
*_protein_disease_genomics_england.csv
*_protein_disease_glyco.csv
*_protein_disease_glycosmos.csv
*_protein_disease_uniprotkb.csv
*_protein_disease_alliance_genome.csv
*_protein_disease_alliance_genome.csv

**Comment by jeet-vora** [comment]
https://github.com/glygener/glygen-issues/issues/853#issuecomment-1854519822
