### ISSUE TITLE
prod and beta api are failing with 502 Proxy Error/500 INTERNAL SERVER ERROR.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#846]
```
https://api.glygen.org/glycan/detail/G17689DH/?query=
{"paginated_tables":[{"table_id":"glycoprotein","offset":1,"limit":20,"sort":"uniprot_canonical_ac","order":"asc"},
{"table_id":"expression_tissue","offset":1,"limit":20,"sort":"start_pos","order":"asc"},
{"table_id":"expression_cell_line","offset":1,"limit":20,"sort":"start_pos","order":"asc"},
{"table_id":"publication","offset":1,"limit":200,"sort":"date","order":"desc"}]}
````
returns 502 Proxy Error

https://api.glygen.org/pages/home_init
returns 502 Proxy Error

https://beta-api.glygen.org/pages/home_init
returns 500 INTERNAL SERVER ERROR

**Comment by rykahsay** [comment]
I think this responses came when the server was acting up. One remedy I did was to use 4 workers instead of one, and hopefully this will fix the problem forever. As far as a user sending it lots of automated requests, we need to talk about how to deal with that.

For now, all the above requests seem to be working

**Comment by sujeetvkulkarni** [comment]
done.
