### ISSUE TITLE
Data files for Nathan

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#871]
@edwardsnj All of the source files we are providing to you are in the following file: https://data.glygen.org/ln2data/downloads/export_files/files4nathan.csv

This file contains the `File Name` and `Path` relative to the downloads directory (https://data.glygen.org/ln2data/downloads/). We've implemented a script to verify that file names are correct, but let me know if you find any issues.

**Example:** 
```
File Name,Path
known_legacy_dbogap_dbogap2_glygen.csv,unicarbkb/current/
```
--> https://data.glygen.org/ln2data/downloads/unicarbkb/current/known_legacy_dbogap_dbogap2_glygen.csv

**Comment by edwardsnj** [comment]
@kmartinez834 @rykahsay This file has a lot less information than the google sheet we were using and does not have any fields which help me understand how it is changing over time. Keeping this file in github would at least allow me to understand changes between versions or whatever. A symbolic (or just an "id") for each entity would make it possible to know that a file has changed name or location rather than being a new file (with the loss of the old one), etc. There are a bunch of rows that are not in "current" of their folders. Lastly, the "characteristics" of the information I should get from each file should be consistent for each grouping. Mixed, or grab-bag, folders should be further subdivided, IMO. Why does export_files say "compiled" not "current"? These are my thoughts as I consider how to use this file.

**Comment by kmartinez834** [comment]
@edwardsnj @rykahsay and I chatted about it this morning, can we discuss on your concerns and address any changes needed on Wednesday?

**Comment by edwardsnj** [comment]
While we are still converging on a process, this ticket is now quite out of date. Closing.
