### ISSUE TITLE
Google form for  "Schedule a GlyGen demo for your Lab" 

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-issues#944]
A form with the request to leave his name + time zone and we will contact them + what interest.

We need to find a place in the static top banner.

**Comment by sujeetvkulkarni** [comment]
1. name
2. email
3. timezone
4. no of people.
5. interest

**Comment by sujeetvkulkarni** [comment]
some comments - 

can we have own form like feedback form etc instead of google form. (Raja)

using date picker? (Raja)
-> I checked after meeting - in google form date picker possible but not with options grayed out in google form (Sujeet).
-> Can we use dropdown for date selection instead of date picker? (Sujeet)

No need of timezone we can consider est by default and use date picker instead. (Raja)

**Comment by sujeetvkulkarni** [comment]
482889cf0c2936475681faef223b922453e1f14e
