### ISSUE TITLE
Check all glycan and protoeform datatsets

### ISSUE THREAD

**Issue by rykahsay** [glygener/glygen-issues#99]
As the result of updating EBI downloads, all glycan and proteoform datasets have been updated. Please use the script check-dataset-group.py to check sanity of these datasets.

**Comment by rykahsay** [comment]
-- the proteoform datasets are still being created, give it few hours and all of them should be there

**Comment by kmartinez834** [comment]
https://github.com/glygener/glygen-issues/issues/92

**Comment by kmartinez834** [comment]
glycan and proteoform dataset issues:
------
- **glycan_top_authors.csv**
Missing 115 authors and many glytoucan ac's
--> Reprocess with all unreviewed/glycan_citations* files as inputs
------
- **sarscov2_proteoform_glycosylation_sites_unicarbkb.csv**
108 rows excluded due to flags:
"unmapped_source_tissue_id(CL_0000738)"
"unmapped_source_tissue_id(leukocyte; CL_0000738)"

- **mouse_proteoform_glycosylation_sites_unicarbkb.csv**
78 rows excluded due to flags:
"unmapped_source_tissue_id(OMIT:0014437; Synaptosomes)"

- **rat_proteoform_glycosylation_sites_unicarbkb.csv**
468 rows excluded due to flags:
"unmapped_source_tissue_id(OMIT:0014437; Synaptosomes)"

--> Is it possible to process all UnicarbKB proteoform files using misc/sample_mapping.csv instead of cellosaurus.txt?

------
- **human_proteoform_glycosylation_sites_unicarbkb.csv**
Missing rows w/ uniprot ac P01106-1
--> generated/datasets/logs are empty for this file

------
- **rat_proteoform_phosphorylation_sites_iptmnet.csv**
"kinase_uniprotkb_canonical_ac","kinase_gene_name" throughout changed from "Q703I1-1","Oser1" to "A0A8I6A4X3-1","Selplg"
```
"uniprotkb_canonical_ac","phosphorylation_site_uniprotkb","amino_acid","kinase_uniprotkb_canonical_ac","kinase_gene_name","xref_key","xref_id","src_xref_key","src_xref_id"
"O08838-1","250","Ser","A0A8I6A4X3-1","Selplg","protein_xref_pelm","O08838","protein_xref_iptmnet","O08838"
```
--> I can't find any evidence in the source file downloads/iptmnet/2022_02/ptm.txt that lists a kinase associated with O08838-1
--> Same for other species, where is the kinase info coming from?

------

**Comment by kmartinez834** [comment]
@rykahsay please see all issues in comment above

**Comment by rykahsay** [comment]
Next time, can you please create separate tickets for each issue

**Comment by rykahsay** [comment]
This issues are fixed, please check. Check usage usage/sarscov2_proteoform_glycosylation_sites_unicarbkb.fu.log 
 now. If you think we should stop using some of the other mapping files, let me know


=======
glycan_top_authors.csv
Missing 115 authors and many glytoucan ac's
--> Reprocess with all unreviewed/glycan_citations* files as inputs

=========
sarscov2_proteoform_glycosylation_sites_unicarbkb.csv
108 rows excluded due to flags:
"unmapped_source_tissue_id(CL_0000738)"
"unmapped_source_tissue_id(leukocyte; CL_0000738)"

mouse_proteoform_glycosylation_sites_unicarbkb.csv
78 rows excluded due to flags:
"unmapped_source_tissue_id(OMIT:0014437; Synaptosomes)"

rat_proteoform_glycosylation_sites_unicarbkb.csv
468 rows excluded due to flags:
"unmapped_source_tissue_id(OMIT:0014437; Synaptosomes)"

**Comment by rykahsay** [comment]
G49108TO is not in unreviewed/glycan_classification.csv, so flag "unknown_glycotype;glycan_without_glytype" is raised as you can see in the logs/unicarbkb/*


<img width="1376" alt="image" src="https://user-images.githubusercontent.com/20584876/223839503-e584c9f9-5e96-4abf-9222-5dcfd047d673.png">

**Comment by rykahsay** [comment]
Fixed --

=======
I can't find any evidence in the source file downloads/iptmnet/2022_02/ptm.txt that lists a kinase associated with O08838-1
--> Same for other species, where is the kinase info coming from?

**Comment by kmartinez834** [comment]
- **mouse_proteoform_glycosylation_sites_unicarbkb.csv, rat_proteoform_glycosylation_sites_unicarbkb.csv, human_proteoform_glycosylation_sites_unicarbkb.csv**
--> see issue #125, G49108TO is O-linked and should be present in glycan_classification.csv

- **rat_proteoform_glycosylation_sites_unicarbkb.csv**
--> see issue #126

👍 glycan_top_authors.csv
👍 sarscov2_proteoform_glycosylation_sites_unicarbkb.csv
👍 rat_proteoform_phosphorylation_sites_iptmnet.csv

**Comment by rykahsay** [comment]
Since the remaining issues have their own ticket now, can you close this?
